CREATE DATABASE IF NOT EXISTS ttrpg_manager CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE ttrpg_manager;

CREATE TABLE users (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(80) NOT NULL,
 email VARCHAR(190) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL,
 role ENUM('DM','PLAYER','GUEST') NOT NULL,
 active BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE auth_tokens (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 user_id BIGINT UNSIGNED NOT NULL,
 selector CHAR(24) NOT NULL UNIQUE,
 validator_hash CHAR(64) NOT NULL,
 last_used_at DATETIME NULL,
 revoked_at DATETIME NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE campaigns (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(120) NOT NULL,
 description TEXT NULL,
 active BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE campaign_members (
 campaign_id BIGINT UNSIGNED NOT NULL,
 user_id BIGINT UNSIGNED NOT NULL,
 PRIMARY KEY(campaign_id,user_id),
 FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE,
 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE assets (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 owner_id BIGINT UNSIGNED NOT NULL,
 mime VARCHAR(80) NOT NULL,
 size_bytes INT UNSIGNED NOT NULL,
 width INT UNSIGNED NOT NULL,
 height INT UNSIGNED NOT NULL,
 path VARCHAR(255) NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE player_characters (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 owner_id BIGINT UNSIGNED NOT NULL,
 campaign_id BIGINT UNSIGNED NOT NULL,
 name VARCHAR(100) NOT NULL,
 avatar_asset_id BIGINT UNSIGNED NULL,
 max_health INT NOT NULL DEFAULT 10,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE,
 FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE,
 FOREIGN KEY (avatar_asset_id) REFERENCES assets(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE dm_player_notes (
 campaign_id BIGINT UNSIGNED NOT NULL,
 player_id BIGINT UNSIGNED NOT NULL,
 notes MEDIUMTEXT NOT NULL,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY(campaign_id,player_id),
 FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE,
 FOREIGN KEY (player_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE scenarios (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 campaign_id BIGINT UNSIGNED NOT NULL,
 name VARCHAR(120) NOT NULL,
 width TINYINT UNSIGNED NOT NULL,
 height TINYINT UNSIGNED NOT NULL,
 background_asset_id BIGINT UNSIGNED NULL,
 active BOOLEAN NOT NULL DEFAULT FALSE,
 version BIGINT UNSIGNED NOT NULL DEFAULT 0,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE,
 FOREIGN KEY (background_asset_id) REFERENCES assets(id) ON DELETE SET NULL,
 CONSTRAINT chk_scenario_size CHECK(width BETWEEN 5 AND 60 AND height BETWEEN 5 AND 60)
) ENGINE=InnoDB;

CREATE TABLE dm_scenario_views (
 campaign_id BIGINT UNSIGNED NOT NULL,
 scenario_id BIGINT UNSIGNED NOT NULL,
 center_x DECIMAL(10,4) NOT NULL DEFAULT 0,
 center_y DECIMAL(10,4) NOT NULL DEFAULT 0,
 zoom DECIMAL(6,4) NOT NULL DEFAULT 1,
 viewed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY(campaign_id,scenario_id),
 FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE,
 FOREIGN KEY (scenario_id) REFERENCES scenarios(id) ON DELETE CASCADE,
 INDEX(campaign_id,viewed_at)
) ENGINE=InnoDB;

CREATE TABLE blocked_cells (
 scenario_id BIGINT UNSIGNED NOT NULL,
 x TINYINT UNSIGNED NOT NULL,
 y TINYINT UNSIGNED NOT NULL,
 PRIMARY KEY(scenario_id,x,y),
 FOREIGN KEY (scenario_id) REFERENCES scenarios(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE cell_notes (
 scenario_id BIGINT UNSIGNED NOT NULL,
 x TINYINT UNSIGNED NOT NULL,
 y TINYINT UNSIGNED NOT NULL,
 notes MEDIUMTEXT NOT NULL,
 PRIMARY KEY(scenario_id,x,y),
 FOREIGN KEY (scenario_id) REFERENCES scenarios(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE map_objects (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 scenario_id BIGINT UNSIGNED NOT NULL,
 name VARCHAR(100) NOT NULL DEFAULT 'Objeto',
 x TINYINT UNSIGNED NOT NULL,
 y TINYINT UNSIGNED NOT NULL,
 width_cells TINYINT UNSIGNED NOT NULL DEFAULT 1,
 height_cells TINYINT UNSIGNED NOT NULL DEFAULT 1,
 offset_x DECIMAL(5,4) NOT NULL DEFAULT .5,
 offset_y DECIMAL(5,4) NOT NULL DEFAULT .5,
 notes MEDIUMTEXT NULL,
 image_asset_id BIGINT UNSIGNED NULL,
 visible BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (scenario_id) REFERENCES scenarios(id) ON DELETE CASCADE,
 FOREIGN KEY (image_asset_id) REFERENCES assets(id) ON DELETE SET NULL,
 INDEX(scenario_id,x,y)
) ENGINE=InnoDB;

CREATE TABLE npc_characters (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 scenario_id BIGINT UNSIGNED NOT NULL,
 name VARCHAR(100) NOT NULL,
 x TINYINT UNSIGNED NOT NULL,
 y TINYINT UNSIGNED NOT NULL,
 notes MEDIUMTEXT NULL,
 image_asset_id BIGINT UNSIGNED NULL,
 health INT NOT NULL DEFAULT 1,
 armor_class INT NULL,
 initiative INT NULL,
 visible BOOLEAN NOT NULL DEFAULT TRUE,
 dead_hidden BOOLEAN NOT NULL DEFAULT FALSE,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (scenario_id) REFERENCES scenarios(id) ON DELETE CASCADE,
 FOREIGN KEY (image_asset_id) REFERENCES assets(id) ON DELETE SET NULL,
 INDEX(scenario_id,x,y)
) ENGINE=InnoDB;

CREATE TABLE scenario_players (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 scenario_id BIGINT UNSIGNED NOT NULL,
 user_id BIGINT UNSIGNED NOT NULL,
 character_id BIGINT UNSIGNED NOT NULL,
 x TINYINT UNSIGNED NOT NULL,
 y TINYINT UNSIGNED NOT NULL,
 health INT NOT NULL,
 initiative INT NULL,
 last_path JSON NULL,
 placed BOOLEAN NOT NULL DEFAULT TRUE,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE(scenario_id,user_id),
 INDEX(user_id,placed),
 FOREIGN KEY (scenario_id) REFERENCES scenarios(id) ON DELETE CASCADE,
 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
 FOREIGN KEY (character_id) REFERENCES player_characters(id) ON DELETE CASCADE,
 INDEX(scenario_id,x,y)
) ENGINE=InnoDB;

CREATE TABLE encounters (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 scenario_id BIGINT UNSIGNED NOT NULL UNIQUE,
 state ENUM('OFF','PREPARING','RUNNING','PAUSED','FINISHED') NOT NULL DEFAULT 'OFF',
 round_no INT UNSIGNED NOT NULL DEFAULT 0,
 current_participant_id BIGINT UNSIGNED NULL,
 turn_sequence INT UNSIGNED NOT NULL DEFAULT 0,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY (scenario_id) REFERENCES scenarios(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE encounter_participants (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 encounter_id BIGINT UNSIGNED NOT NULL,
 actor_type ENUM('PLAYER','NPC') NOT NULL,
 actor_id BIGINT UNSIGNED NOT NULL,
 initiative INT NULL,
 tie_order INT NOT NULL DEFAULT 0,
 state ENUM('ACTIVE','WAITING','DEAD','REMOVED') NOT NULL DEFAULT 'ACTIVE',
 UNIQUE(encounter_id,actor_type,actor_id),
 FOREIGN KEY (encounter_id) REFERENCES encounters(id) ON DELETE CASCADE,
 INDEX(encounter_id,initiative,tie_order)
) ENGINE=InnoDB;

ALTER TABLE encounters ADD CONSTRAINT fk_encounter_current FOREIGN KEY (current_participant_id) REFERENCES encounter_participants(id) ON DELETE SET NULL;

CREATE TABLE turn_delays (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 encounter_id BIGINT UNSIGNED NOT NULL,
 waiting_participant_id BIGINT UNSIGNED NOT NULL,
 target_participant_id BIGINT UNSIGNED NOT NULL,
 round_no INT UNSIGNED NOT NULL,
 sort_order INT NOT NULL DEFAULT 0,
 triggered BOOLEAN NOT NULL DEFAULT FALSE,
 FOREIGN KEY (encounter_id) REFERENCES encounters(id) ON DELETE CASCADE,
 FOREIGN KEY (waiting_participant_id) REFERENCES encounter_participants(id) ON DELETE CASCADE,
 FOREIGN KEY (target_participant_id) REFERENCES encounter_participants(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE movement_requests (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 scenario_id BIGINT UNSIGNED NOT NULL,
 user_id BIGINT UNSIGNED NOT NULL,
 path JSON NOT NULL,
 status ENUM('PENDING','APPROVED','REJECTED','APPLIED') NOT NULL,
 reason VARCHAR(255) NULL,
 reviewed_by BIGINT UNSIGNED NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY (scenario_id) REFERENCES scenarios(id) ON DELETE CASCADE,
 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
 FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE scenario_events (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 scenario_id BIGINT UNSIGNED NOT NULL,
 version BIGINT UNSIGNED NOT NULL,
 event_type VARCHAR(80) NOT NULL,
 actor_id BIGINT UNSIGNED NULL,
 payload JSON NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(scenario_id,version),
 FOREIGN KEY (scenario_id) REFERENCES scenarios(id) ON DELETE CASCADE,
 FOREIGN KEY (actor_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE command_receipts (
 request_id VARCHAR(64) PRIMARY KEY,
 user_id BIGINT UNSIGNED NOT NULL,
 response JSON NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
 INDEX(created_at)
) ENGINE=InnoDB;

CREATE TABLE dm_lease (
 lease_key TINYINT PRIMARY KEY DEFAULT 1,
 user_id BIGINT UNSIGNED NOT NULL,
 connection_id VARCHAR(80) NOT NULL,
 expires_at DATETIME NOT NULL,
 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

INSERT INTO campaigns(name,description) VALUES ('Campaña principal','Campaña inicial del grupo');
