USE dnd_manager;

ALTER TABLE map_objects
    ADD COLUMN IF NOT EXISTS width_cells TINYINT UNSIGNED NOT NULL DEFAULT 1 AFTER y,
    ADD COLUMN IF NOT EXISTS height_cells TINYINT UNSIGNED NOT NULL DEFAULT 1 AFTER width_cells;
