USE dnd_manager;

-- Wikidot lineage/species support. Base lineages go into `species`; child lineages/variants
-- such as Hill Dwarf, High Elf, Draconblood, etc. go into `subspecies`.

ALTER TABLE species
 ADD COLUMN IF NOT EXISTS lineage_type_code VARCHAR(60) NULL AFTER source_page_text,
 ADD COLUMN IF NOT EXISTS wikidot_slug VARCHAR(120) NULL AFTER lineage_type_code,
 ADD COLUMN IF NOT EXISTS source_url VARCHAR(500) NULL AFTER wikidot_slug,
 ADD COLUMN IF NOT EXISTS is_ua BOOLEAN NOT NULL DEFAULT FALSE AFTER source_url,
 ADD COLUMN IF NOT EXISTS is_setting_specific BOOLEAN NOT NULL DEFAULT FALSE AFTER is_ua,
 ADD COLUMN IF NOT EXISTS creature_type_text VARCHAR(255) NULL AFTER ability_score_text,
 ADD COLUMN IF NOT EXISTS age_text VARCHAR(500) NULL AFTER creature_type_text,
 ADD COLUMN IF NOT EXISTS alignment_text VARCHAR(500) NULL AFTER age_text,
 ADD COLUMN IF NOT EXISTS raw_data_json LONGTEXT NULL AFTER traits_text,
 ADD UNIQUE KEY IF NOT EXISTS uq_species_wikidot_source (system_id, wikidot_slug, source_material_id),
 ADD INDEX IF NOT EXISTS idx_species_lineage_type (lineage_type_code);

CREATE TABLE IF NOT EXISTS subspecies (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 system_id BIGINT UNSIGNED NOT NULL,
 species_id BIGINT UNSIGNED NOT NULL,
 visibility_level_id BIGINT UNSIGNED NOT NULL,
 source_subspecies_id BIGINT UNSIGNED NULL,
 created_by_user_id BIGINT UNSIGNED NULL,
 source_material_id BIGINT UNSIGNED NULL,
 source_page_text VARCHAR(80) NULL,
 lineage_type_code VARCHAR(60) NULL,
 wikidot_slug VARCHAR(120) NULL,
 source_url VARCHAR(500) NULL,
 is_ua BOOLEAN NOT NULL DEFAULT FALSE,
 is_setting_specific BOOLEAN NOT NULL DEFAULT FALSE,
 name VARCHAR(160) NOT NULL,
 short_description VARCHAR(500) NULL,
 description MEDIUMTEXT NOT NULL,
 size_text VARCHAR(255) NULL,
 speed_text VARCHAR(255) NULL,
 languages_text VARCHAR(500) NULL,
 ability_score_text VARCHAR(500) NULL,
 creature_type_text VARCHAR(255) NULL,
 age_text VARCHAR(500) NULL,
 alignment_text VARCHAR(500) NULL,
 traits_text MEDIUMTEXT NULL,
 raw_data_json LONGTEXT NULL,
 is_custom BOOLEAN NOT NULL DEFAULT FALSE,
 is_active BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE KEY uq_subspecies_wikidot_source (system_id, species_id, wikidot_slug, name, source_material_id),
 INDEX idx_subspecies_search (system_id, name),
 INDEX idx_subspecies_species (species_id),
 INDEX idx_subspecies_visibility (visibility_level_id),
 INDEX idx_subspecies_source_material (source_material_id),
 INDEX idx_subspecies_lineage_type (lineage_type_code),
 FOREIGN KEY (system_id) REFERENCES systems(id) ON DELETE RESTRICT,
 FOREIGN KEY (species_id) REFERENCES species(id) ON DELETE CASCADE,
 FOREIGN KEY (visibility_level_id) REFERENCES visibility_levels(id) ON DELETE RESTRICT,
 FOREIGN KEY (source_subspecies_id) REFERENCES subspecies(id) ON DELETE SET NULL,
 FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
 FOREIGN KEY (source_material_id) REFERENCES sources(id) ON DELETE SET NULL
) ENGINE=InnoDB;
