USE dnd_manager;

ALTER TABLE backgrounds
 ADD COLUMN IF NOT EXISTS background_type_code VARCHAR(60) NULL AFTER source_page_text,
 ADD COLUMN IF NOT EXISTS setting_name VARCHAR(160) NULL AFTER background_type_code,
 ADD COLUMN IF NOT EXISTS wikidot_slug VARCHAR(120) NULL AFTER setting_name,
 ADD COLUMN IF NOT EXISTS source_url VARCHAR(500) NULL AFTER wikidot_slug,
 ADD COLUMN IF NOT EXISTS prerequisites_text TEXT NULL AFTER source_url,
 ADD COLUMN IF NOT EXISTS is_setting_specific BOOLEAN NOT NULL DEFAULT FALSE AFTER prerequisites_text,
 ADD COLUMN IF NOT EXISTS is_homebrew BOOLEAN NOT NULL DEFAULT FALSE AFTER is_setting_specific,
 ADD COLUMN IF NOT EXISTS is_adventurers_league BOOLEAN NOT NULL DEFAULT FALSE AFTER is_homebrew,
 ADD COLUMN IF NOT EXISTS raw_data_json LONGTEXT NULL AFTER suggested_characteristics_text,
 ADD UNIQUE KEY IF NOT EXISTS uq_backgrounds_wikidot_source (system_id, wikidot_slug, source_material_id),
 ADD INDEX IF NOT EXISTS idx_backgrounds_type (background_type_code),
 ADD INDEX IF NOT EXISTS idx_backgrounds_setting (setting_name);

CREATE TABLE IF NOT EXISTS background_variants (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 system_id BIGINT UNSIGNED NOT NULL,
 background_id BIGINT UNSIGNED NOT NULL,
 visibility_level_id BIGINT UNSIGNED NOT NULL,
 source_background_variant_id BIGINT UNSIGNED NULL,
 created_by_user_id BIGINT UNSIGNED NULL,
 source_material_id BIGINT UNSIGNED NULL,
 source_page_text VARCHAR(80) NULL,
 background_type_code VARCHAR(60) NULL,
 setting_name VARCHAR(160) NULL,
 wikidot_slug VARCHAR(120) NULL,
 source_url VARCHAR(500) NULL,
 prerequisites_text TEXT NULL,
 name VARCHAR(160) NOT NULL,
 short_description VARCHAR(500) NULL,
 description MEDIUMTEXT NOT NULL,
 skill_proficiencies_text VARCHAR(500) NULL,
 tool_proficiencies_text VARCHAR(500) NULL,
 languages_text VARCHAR(500) NULL,
 equipment_text TEXT NULL,
 feature_text MEDIUMTEXT NULL,
 suggested_characteristics_text MEDIUMTEXT NULL,
 is_setting_specific BOOLEAN NOT NULL DEFAULT FALSE,
 is_homebrew BOOLEAN NOT NULL DEFAULT FALSE,
 is_adventurers_league BOOLEAN NOT NULL DEFAULT FALSE,
 raw_data_json LONGTEXT NULL,
 is_custom BOOLEAN NOT NULL DEFAULT FALSE,
 is_active BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE KEY uq_background_variants_wikidot_source (system_id, background_id, wikidot_slug, name, source_material_id),
 INDEX idx_background_variants_search (system_id, name),
 INDEX idx_background_variants_background (background_id),
 INDEX idx_background_variants_visibility (visibility_level_id),
 INDEX idx_background_variants_source_material (source_material_id),
 FOREIGN KEY (system_id) REFERENCES systems(id) ON DELETE RESTRICT,
 FOREIGN KEY (background_id) REFERENCES backgrounds(id) ON DELETE CASCADE,
 FOREIGN KEY (visibility_level_id) REFERENCES visibility_levels(id) ON DELETE RESTRICT,
 FOREIGN KEY (source_background_variant_id) REFERENCES background_variants(id) ON DELETE SET NULL,
 FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
 FOREIGN KEY (source_material_id) REFERENCES sources(id) ON DELETE SET NULL
) ENGINE=InnoDB;
